<?php

namespace BlogBundle\Repository;

/**
 * Post_UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Post_UserRepository extends \Doctrine\ORM\EntityRepository
{
}
